# Generated by Django 2.0 on 2017-12-22 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('comment_time', models.DateTimeField(auto_now=True)),
                ('comment_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_text', models.TextField()),
                ('post_replies', models.IntegerField(default=0)),
                ('post_views', models.IntegerField(default=0)),
                ('post_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_title', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_login', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('user_pass', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=200, unique=True)),
                ('user_name', models.CharField(max_length=200)),
                ('user_image', models.ImageField(upload_to='users/images/')),
                ('post_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Section'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.User'),
        ),
    ]
