# Generated by Django 2.0 on 2017-12-22 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_subsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsection',
            name='subsection_section',
            field=models.ForeignKey(default='a', on_delete=django.db.models.deletion.CASCADE, to='forum.Section'),
            preserve_default=False,
        ),
    ]
