# Generated by Django 2.0 on 2017-12-22 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_subsection_subsection_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Subsection'),
        ),
    ]
