# Generated by Django 2.0 on 2017-12-22 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20171222_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_section',
            new_name='post_subsection',
        ),
    ]
