# Generated by Django 2.0 on 2017-12-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20171227_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(default='users/default/default_img.jpg', upload_to='users/images/'),
        ),
    ]
