# Generated by Django 2.0 on 2017-12-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20171222_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_answer',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
