# Generated by Django 2.0 on 2017-12-22 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20171222_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_replies',
        ),
        migrations.RemoveField(
            model_name='user',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='post_count',
        ),
    ]
