# Generated by Django 2.0 on 2017-12-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20171226_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
        migrations.AddField(
            model_name='user',
            name='user_first_name',
            field=models.CharField(default='Default', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_last_name',
            field=models.CharField(default='Last', max_length=100),
            preserve_default=False,
        ),
    ]
