# Generated by Django 2.0 on 2017-12-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_auto_20171226_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='users/default/default_img.jpg', upload_to='users/images/'),
        ),
    ]
